mysql:
  host: localhost
  port: 3306
  database: scientist
  user: root
  password: password
  pool:
    maxPoolSize: 10
    minimumIdle: 2

experiments:
  max_concurrent_per_player: 1
  default_duration_hours: 4

drops_settings:
  min_level_for_drops: 45

drops_by_mythic:
  note: "Drops handled by mythic_drops patterns and tier suffixes (inf=I, hell=II, blood=III)."

mythic_drops:
  enabled: true
  tier_by_suffix:
    inf: I
    hell: II
    blood: III
  tier_chance:
    I: 0.08
    II: 0.04
    III: 0.015
  default_families: [ void_shard, soul_residue ]
  groups:
    Q1:
      pattern: "(flamecult|perral_world_dragonknight|raazghul|grimmag)"
      families: [ ember_powder, storm_pearl ]
    Q2:
      pattern: "(gremlin|death_witch|poisonous_spider|root_creature|xerib|archus|arachna)"
      families: [ rift_fibre, soul_residue ]
    Q3:
      pattern: "(cursed_|slain_|evil_miller|heredur)"
      families: [ shadow_ash, frost_core ]
    Q4:
      pattern: "(sanguine_clan|eternal_|bearach|lightning_wolf)"
      families: [ ancient_bone_dust, gloom_lotus ]
    Q5:
      pattern: "(maggot|andermagic|khalys|wandering_experiment)"
      families: [ void_shard, eldritch_ichor ]
    Q6:
      pattern: "(fallen_|death_knight|mortis|skeleton|murot|skeledragon)"
      families: [ soul_residue, ancient_bone_dust ]
    Q7:
      pattern: "(bone_warder|mechanoid|cyclops|dark_sentinel|flame|herald_of_anderworld|embersword)"
      families: [ ember_powder, void_shard ]
    Q8:
      pattern: "(frost|sigrismarr|ice|wolf|troll)"
      families: [ frost_core, storm_pearl ]
    Q9:
      pattern: "(satyr|cohort|stone_golem|minotaur|gorgon|medusa|zorlobb|ebicarus|asterion|snake_minion)"
      families: [ rift_fibre, gloom_lotus ]
    Q10:
      pattern: "(gorgon|jitterjelly|zorlobb|khaross|gorga|akheilos)"
      families: [ storm_pearl, rift_fibre ]
    T1:
      pattern: "(shadow|umbral|void_)"
      families: [ shadow_ash, void_shard ]
    T2:
      pattern: "(aquatic|sea|coral|abyssal|kraken|poseidon)"
      families: [ storm_pearl, ember_powder ]
    T3:
      pattern: "(celestial|olymp|divine|zeus|storm_bringer)"
      families: [ storm_pearl, void_shard ]
    T4:
      pattern: "(bronze|labyrinth|clockwork|minotaur_mechanicus)"
      families: [ rift_fibre, ancient_bone_dust ]
    T5:
      pattern: "(soul|ethereal|immortal|lich|thanatos|hades)"
      families: [ soul_residue, ancient_bone_dust ]

drops:
  # Example drop config per entity type (extend as needed)
  ZOMBIE:
    corrupted_petal_I: 0.12
    corrupted_petal_II: 0.04
    corrupted_petal_III: 0.01
    gloom_lotus_I: 0.08
    gloom_lotus_II: 0.03
    gloom_lotus_III: 0.01
  SKELETON:
    blood_amber_I: 0.06
    blood_amber_II: 0.03
    blood_amber_III: 0.01
    ancient_bone_dust_I: 0.10
    ancient_bone_dust_II: 0.04
    ancient_bone_dust_III: 0.015
    void_shard_I: 0.05
    void_shard_II: 0.02
    void_shard_III: 0.008
  SPIDER:
    rift_fibre_I: 0.10
    rift_fibre_II: 0.05
    rift_fibre_III: 0.02
    shadow_ash_I: 0.06
    shadow_ash_II: 0.03
    shadow_ash_III: 0.01
  ENDERMAN:
    storm_pearl_I: 0.10
    storm_pearl_II: 0.05
    storm_pearl_III: 0.02
  CREEPER:
    ember_powder_I: 0.08
    ember_powder_II: 0.04
    ember_powder_III: 0.015
  DROWNED:
    blood_amber_I: 0.05
    blood_amber_II: 0.025
    blood_amber_III: 0.01
  HUSK:
    soul_residue_I: 0.07
    soul_residue_II: 0.035
    soul_residue_III: 0.012
  STRAY:
    frost_core_I: 0.10
    frost_core_II: 0.05
    frost_core_III: 0.02

roll_rules:
  choice_count: 2
  ensure_distinct: true
  allow_wildcards: true
  wildcard_chance_by_tier:
    1: 0.10
    2: 0.15
    3: 0.20

debug:
  mode: false
  short_experiments_seconds: 5
  default_reagents:
    - void_shard_I
    - soul_residue_I
shortcuts:
  scientist:
    command: "scientist"
    permission: "mycraftingplugin.use"

