package pl.yourserver.scientistPlugin.model;

public enum SciCategory {
    WEAPON,
    ARMOR_HELM, ARMOR_CHEST, ARMOR_LEGS, ARMOR_BOOTS,
    ACCESSORY_RING1, ACCESSORY_RING2, ACCESSORY_NECKLACE,
    ACCESSORY_ADORNMENT, ACCESSORY_CLOAK, ACCESSORY_SHIELD,
    ACCESSORY_BELT, ACCESSORY_GLOVES;
}

